### ISSUE TITLE
Travis CI を設定する

### ISSUE THREAD

**Issue by tkoyama010** [OpenFOAM-jp/OpenFOAM-jp#1]
Travis CI を設定を設定しpushした段階でテストを行います。テストを行うスクリプトを教えていただけますか。

**Comment by inabower** [comment]
こんな感じでしょうか

```yaml
sudo: required
dist: bionic
language: Rust
before_install:
#- mkdir -p ~/.ssh
#- touch ~/.ssh/id_rsa
#- chmod 600 ~/.ssh/id_rsa
#- openssl aes-256-cbc -K $encrypted_b66af6951016_key -iv $encrypted_b66af6951016_iv -in .secrets/key.enc -out ~/.ssh/id_rsa -d
#- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- sudo apt-get install -y --no-install-recommends git-core build-essential cmake libfl-dev bison zlib1g-dev qt4-dev-tools libqt4-dev libqtwebkit-dev gnuplot \
libreadline-dev libncurses-dev libxt-dev libopenmpi-dev openmpi-bin libboost-system-dev libboost-thread-dev libgmp-dev \
libmpfr-dev python python-dev libcgal-dev curl
addons:
  apt:
    update: true
script:before_install:
- source etc/bashrc
- git clone https://github.com/kurenaif/auto_wmake.git ../auto_wmake
- cd ../auto_wmake
- cargo build
addons:
  apt:
    update: true
script:
- cd ~
- cargo run mergeMeshes
after_success:
- echo "Success!!"
#after_success:
- git branch -a
- git checkout develop
- git add symposium/TeX/*.pdf
- git commit -m "[skip ci] by Travis CI (JOB $TRAVIS_JOB_NUMBER)
  https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID"
- git remote -v
- git remote add github git@github.com:OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium.git
- git push github develop
```
